# Generated by Django 3.0.5 on 2021-02-05 04:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField(max_length=3, validators=[django.core.validators.MinValueValidator(1)])),
                ('account_balance', models.IntegerField(max_length=8, validators=[django.core.validators.MinValueValidator(7000)])),
            ],
        ),
    ]
